version: "3.9"
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: pong
      POSTGRES_USER: pong
      POSTGRES_PASSWORD: pong
